In [112]:
import time
import numpy as np
import os
import copy

initial_state = []


def get_initial():
    print("Enter number from 0-8")
    initial_state = np.zeros(9)
    for i in range(9):
        states = int(input("Enter the number: "))
        initial_state[i] = np.array(states)
    print(initial_state)
    initial_state = np.reshape(initial_state,(3,3))
    return initial_state


def find_index(puzzle):
    for i in range(3):
        for j in range(3):
            if puzzle[i][j] == 0:
                return i,j

#def blank_tile_location(A):
    #loc = np.argwhere(A == 0)
    #return loc            
            

def move_left(data):
    temp_arr = copy.deepcopy(data)
    i, j = find_index(temp_arr)
    if j != 0:
        temp = temp_arr[i, j - 1]
        temp_arr[i, j] = temp
        temp_arr[i, j - 1] = 0
        print("Left motion")
        return temp_arr
    else:
        print("No left motion")
        return temp_arr


def move_right(data):
    temp_arr = copy.deepcopy(data)
    i, j = find_index(data)
    if j != 2:
        temp = temp_arr[i, j + 1]
        temp_arr[i, j] = temp
        temp_arr[i, j + 1] = 0
        print("Right motion")
        return temp_arr
    else:
        print("No right motion")
        return temp_arr

def move_up(data):
    temp_arr = copy.deepcopy(data)
    i, j = find_index(data)
    if i != 0:
        temp_arr = np.copy(data)
        temp = temp_arr[i - 1, j]
        temp_arr[i, j] = temp
        temp_arr[i - 1, j] = 0
        print("Up motion")
        return temp_arr
    else:
        print("No up motion")
        return temp_arr


def move_down(data):
    temp_arr = copy.deepcopy(data)
    i, j = find_index(data)
    if i != 2:
        temp_arr = np.copy(data)
        temp = temp_arr[i + 1, j]
        temp_arr[i, j] = temp
        temp_arr[i + 1, j] = 0
        print("Down motion")
        return temp_arr
        
    else:
        print("No down motion")
        return temp_arr

def sol(ip_node):
    z = []
    inv = 0
    for i in range(3):
        for j in range(3):
            if (ip_node[i][j]!=0):
                z.append(ip_node[i][j])            
    for i in range(7):
        j=i+1
        while(j<8):
            if z[i]>z[j]:
                inv += 1
            j += 1
    if inv % 2:
        print("Unsolvable")
        return 0
    else:
        print("Solvable")
        return 1


#to check and append in the parent node
def check_and_append(p_node, new_node, count):
    stat=False
    q = 1
    
    for l in p_node:
        if (l == new_node).all():  
            q = 0
            print("Not equal, Not appended")
            
    
    if q == 1:
        print("Appended")
        visited_nodes.append(new_node)
        stat=True
    return count, stat


# to check if the goal is reached
def goal_check(B,goal_node):
    status = np.array_equal(B,goal_node)
    return status

# initializing the goal node
goal_node = np.array([[1,2,3],[4,5,6],[7,8,0]])

start_time=time.time()

visited_nodes=[]
initial_array = get_initial()
visited_nodes.append(initial_array)
child_node_number=1
print("child index total")
print(visited_nodes)
print("child index 1.")
print(visited_nodes[0])
temp_index = []
i=0


if (sol(initial_array)):

    while (i < child_node_number):

        node_list = visited_nodes[i]


        new_node = move_left(node_list)
        print(new_node)
        child_node_number, status = check_and_append(visited_nodes, new_node, child_node_number)
        print(status)
        if status == True:
            child_node_number += 1
            temp_index.append(child_node_number)


        if goal_check(new_node,goal_node):
            found = True
            break




        new_node = move_up(node_list)
        print(new_node)
        child_node_number, status=check_and_append(visited_nodes, new_node, child_node_number)
        print(status)
        if status == True:
            child_node_number += 1
            temp_index.append(child_node_number)


        if goal_check(new_node,goal_node):
            found = True       
            break



        new_node = move_right(node_list)
        print(new_node)
        child_node_number, status=check_and_append(visited_nodes, new_node, child_node_number)
        print(status)
        if status == True: 
            child_node_number += 1
            temp_index.append(child_node_number)


        if goal_check(new_node,goal_node):
            found = True
            break



        new_node = move_down(node_list)
        print(new_node)
        child_node_number, status=check_and_append(visited_nodes, new_node, child_node_number)
        print(status)
        if status == True:
            child_node_number += 1
            temp_index.append(child_node_number)

        if goal_check(new_node,goal_node):
            found = True
            break


            print(visited_nodes)    
            print(child_node_number)
        i+=1

print("total time:")
print(time.time()-start_time) 


Enter number from 0-8
Enter the number: 1
Enter the number: 0
Enter the number: 3
Enter the number: 4
Enter the number: 2
Enter the number: 5
Enter the number: 7
Enter the number: 8
Enter the number: 6
[ 1.  0.  3.  4.  2.  5.  7.  8.  6.]
child index total
[array([[ 1.,  0.,  3.],
       [ 4.,  2.,  5.],
       [ 7.,  8.,  6.]])]
child index 1.
[[ 1.  0.  3.]
 [ 4.  2.  5.]
 [ 7.  8.  6.]]
Solvable
Left motion
[[ 0.  1.  3.]
 [ 4.  2.  5.]
 [ 7.  8.  6.]]
Appended
True
No up motion
[[ 1.  0.  3.]
 [ 4.  2.  5.]
 [ 7.  8.  6.]]
Not equal, Not appended
False
Right motion
[[ 1.  3.  0.]
 [ 4.  2.  5.]
 [ 7.  8.  6.]]
Appended
True
Down motion
[[ 1.  2.  3.]
 [ 4.  0.  5.]
 [ 7.  8.  6.]]
Appended
True
No left motion
[[ 0.  1.  3.]
 [ 4.  2.  5.]
 [ 7.  8.  6.]]
Not equal, Not appended
False
No up motion
[[ 0.  1.  3.]
 [ 4.  2.  5.]
 [ 7.  8.  6.]]
Not equal, Not appended
False
Right motion
[[ 1.  0.  3.]
 [ 4.  2.  5.]
 [ 7.  8.  6.]]
Not equal, Not appended
False
Down motion
[[ 4.  1. 

## node_list

In [110]:
visited_nodes

[array([[ 1.,  0.,  3.],
        [ 4.,  2.,  5.],
        [ 7.,  8.,  6.]]), array([[ 0.,  1.,  3.],
        [ 4.,  2.,  5.],
        [ 7.,  8.,  6.]]), array([[ 1.,  3.,  0.],
        [ 4.,  2.,  5.],
        [ 7.,  8.,  6.]]), array([[ 1.,  2.,  3.],
        [ 4.,  0.,  5.],
        [ 7.,  8.,  6.]]), array([[ 4.,  1.,  3.],
        [ 0.,  2.,  5.],
        [ 7.,  8.,  6.]]), array([[ 1.,  3.,  5.],
        [ 4.,  2.,  0.],
        [ 7.,  8.,  6.]]), array([[ 1.,  2.,  3.],
        [ 0.,  4.,  5.],
        [ 7.,  8.,  6.]]), array([[ 1.,  2.,  3.],
        [ 4.,  5.,  0.],
        [ 7.,  8.,  6.]]), array([[ 1.,  2.,  3.],
        [ 4.,  8.,  5.],
        [ 7.,  0.,  6.]]), array([[ 4.,  1.,  3.],
        [ 2.,  0.,  5.],
        [ 7.,  8.,  6.]]), array([[ 4.,  1.,  3.],
        [ 7.,  2.,  5.],
        [ 0.,  8.,  6.]]), array([[ 1.,  3.,  5.],
        [ 4.,  0.,  2.],
        [ 7.,  8.,  6.]]), array([[ 1.,  3.,  5.],
        [ 4.,  2.,  6.],
        [ 7.,  8.,  0.]]), array([[ 0.

# state = get_initial()

In [3]:
temp_index

[3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239,
 241,
 243,
 245,
 247,
 249,
 251,
 253,
 255,
 257,
 259,
 261,
 263,
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 299,
 301,
 303,
 305,
 307,
 309,
 311,
 313,
 315,
 317,
 319,
 321,
 323,
 325,
 327,
 329,
 331,
 333,
 335,
 337,
 339,
 341]

In [ ]:
first_node = copy.deepcopy(state)
print(state)

In [ ]:
visited_nodes[16]

In [ ]:
find_index(first_node)

In [6]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [7]:
x = move_down(state)

Down motion


In [8]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  5.],
       [ 6.,  0.,  8.]])

In [9]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [10]:
y = move_up(state)
    

Up motion


In [11]:
y

array([[ 1.,  0.,  3.],
       [ 4.,  2.,  5.],
       [ 6.,  7.,  8.]])

In [12]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [13]:
z = move_left(state)

Left motion


In [14]:
z


array([[ 1.,  2.,  3.],
       [ 0.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [17]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [15]:
p = move_right(state)

Right motion


In [16]:
p

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  0.],
       [ 6.,  7.,  8.]])

In [18]:
goal_node

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])