In [2]:

import numpy as np
import os  
import copy

initial_state = []


def get_initial():
    print("Enter number from 0-8")
    initial_state = np.zeros(9)
    for i in range(9):
        states = int(input("Enter the number: "))
        initial_state[i] = np.array(states)
        print(initial_state)
    initial_state = np.reshape(initial_state,(3,3))
    return initial_state


def find_index(puzzle):
    for i in range(len(puzzle[0])):
        for j in range(len(puzzle[0])):
            if puzzle[i][j] == 0:
                return i,j
            

def move_left(data):
    temp_arr = copy.deepcopy(data)
    i, j = find_index(temp_arr)
    if j != 0:
        temp = temp_arr[i, j - 1]
        temp_arr[i, j] = temp
        temp_arr[i, j - 1] = 0
        print("Left motion")
        return temp_arr
    else:
        print("No left motion")
        return None


def move_right(data):
    i, j = find_index(data)
    if j != 2:
        temp_arr = np.copy(data)
        temp = temp_arr[i, j + 1]
        temp_arr[i, j] = temp
        temp_arr[i, j + 1] = 0
        print("Right motion")
        return temp_arr
    else:
        print("No right motion")
        return None

def move_up(data):
    i, j = find_index(data)
    if i != 0:
        temp_arr = np.copy(data)
        temp = temp_arr[i - 1, j]
        temp_arr[i, j] = temp
        temp_arr[i - 1, j] = 0
        print("Up motion")
        return temp_arr
    else:
        print("No up motion")
        return None


def move_down(data):
    i, j = find_index(data)
    if i != 2:
        temp_arr = np.copy(data)
        temp = temp_arr[i + 1, j]
        temp_arr[i, j] = temp
        temp_arr[i + 1, j] = 0
        print("Down motion")
        return temp_arr
        
    else:
        print("No down motion")
        return None

#to check and append in the parent node
def check_and_append(p_node, new_node, count):
    
    for i in range(count):
        if (p_node[i]==new_node):  
            j=0
            break
        
    if j:
        p_node.append(new_node)
        count+=1
    return p_node, count

# to check if the goal is reached
def goal_check(B,goal_node):
    status = np.array_equal(B,goal_node)
    return status

# initializing the goal node
goal_node = np.array([[1,2,3],[4,5,6],[7,8,0]])

child_index=[]

while len(child_index)>0:

    temp_index = []
    for i in child_index:

        new_node, status = move_up(node_list)

        if status == True:
            child_node_number += 1
            temp_index.append(child_node_number)
            node_list.append(new_node)
            temp_node_info = np.array([child_node_number,i,0])
            node_info.append(temp_node_info)
            node_set.add(set_conversion(new_node))

            if goal_check(new_node,goal_node):
                found = True
                goal_index = child_node_number
                break

        new_node, status = move_down(node_list[i])

        if status == True:
            child_node_number += 1
            node_list.append(new_node)
            temp_node_info = np.array([child_node_number,i,0])
            node_info.append(temp_node_info)
            temp_index.append(child_node_number)
            node_set.add(set_conversion(new_node))
    
            if goal_check(new_node,goal_node):
                found = True
                goal_index = child_node_number
                break

        new_node, status = move_right(node_list[i])

        if status == True: 
            child_node_number += 1
            node_list.append(new_node)
            temp_node_info = np.array([child_node_number,i,0])
            node_info.append(temp_node_info)
            temp_index.append(child_node_number)
            node_set.add(set_conversion(new_node))
    
            if goal_check(new_node,goal_node):
                found = True
                goal_index = child_node_number
                break

        new_node, status = move_left(node_list[i])

        if status == True:
            child_node_number += 1
            node_list.append(new_node)
            temp_node_info = np.array([child_node_number,i,0])
            node_info.append(temp_node_info)
            temp_index.append(child_node_number)
            node_set.add(set_conversion(new_node))
    
            if goal_check(new_node,goal_node):
                found = True
                goal_index = child_node_number
                break





In [3]:
state = get_initial()

Enter number from 0-8
Enter the number: 1
[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
Enter the number: 2
[ 1.  2.  0.  0.  0.  0.  0.  0.  0.]
Enter the number: 3
[ 1.  2.  3.  0.  0.  0.  0.  0.  0.]
Enter the number: 4
[ 1.  2.  3.  4.  0.  0.  0.  0.  0.]
Enter the number: 0
[ 1.  2.  3.  4.  0.  0.  0.  0.  0.]
Enter the number: 5
[ 1.  2.  3.  4.  0.  5.  0.  0.  0.]
Enter the number: 6
[ 1.  2.  3.  4.  0.  5.  6.  0.  0.]
Enter the number: 7
[ 1.  2.  3.  4.  0.  5.  6.  7.  0.]
Enter the number: 8
[ 1.  2.  3.  4.  0.  5.  6.  7.  8.]


In [4]:
first_node = copy.deepcopy(state)
print(state)

[[ 1.  2.  3.]
 [ 4.  0.  5.]
 [ 6.  7.  8.]]


In [5]:
find_index(first_node)

(1, 1)

In [6]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [7]:
x = move_down(state)

Down motion


In [8]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  5.],
       [ 6.,  0.,  8.]])

In [9]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [10]:
y = move_up(state)
    

Up motion


In [11]:
y

array([[ 1.,  0.,  3.],
       [ 4.,  2.,  5.],
       [ 6.,  7.,  8.]])

In [12]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [13]:
z = move_left(state)

Left motion


In [14]:
z


array([[ 1.,  2.,  3.],
       [ 0.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [17]:
state

array([[ 1.,  2.,  3.],
       [ 4.,  0.,  5.],
       [ 6.,  7.,  8.]])

In [15]:
p = move_right(state)

Right motion


In [16]:
p

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  0.],
       [ 6.,  7.,  8.]])

In [18]:
goal_node

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])